//Helmet images
import Helmet6B47 from './Tarkov_Helmets/6B47.webp' 
import HelmetACHHC from './Tarkov_Helmets/ACHHC.webp' 
import HelmetAltyn from './Tarkov_Helmets/Altynimage.webp' 
import HelmetArmasightnvg from './Tarkov_Helmets/Armasight_NVG_Mask.webp' 
import HelmetBastion from './Tarkov_Helmets/Bastion_View.webp' 
import HelmetBomerBeanie from './Tarkov_Helmets/Bomber_Beanie.webp' 
import HelmetCaiman from './Tarkov_Helmets/Caiman.webp' 
import HelmetAirFrame from './Tarkov_Helmets/Crye_Precision_Airframe_Tan_Image.webp' 
import HelmetRonin from './Tarkov_Helmets/DEVTAC_Ronin_ballistic_helmet_Image.webp' 
import HelmetFastmt from './Tarkov_Helmets/FASTMT.webp' 
import HelmetHJELM from './Tarkov_Helmets/HJELM.webp' 
import HelmetKiverM from './Tarkov_Helmets/Kiver-M_Helmet.webp' 
import HelmetKolpak1S from './Tarkov_Helmets/Kolpak-1S.webp' 
import HelmetLSHZ from './Tarkov_Helmets/LSHZ-2DTM3D.webp' 
import HelmetLZSh from './Tarkov_Helmets/LZSh_light_helmet.webp' 
import HelmetMaska from './Tarkov_Helmets/Maska_1Sch_helmet.webp' 
import HelmetMich2002 from './Tarkov_Helmets/MICH_2002_View.PNG.webp' 
import HelmetMich from './Tarkov_Helmets/Mich_View.PNG.webp' 
import HelmetMSATC800 from './Tarkov_Helmets/MSA_TC_800.webp' 
import HelmetPSH97 from './Tarkov_Helmets/PSH-97_-Jeta-_helmet_Image.webp' 
import HelmetRysT from './Tarkov_Helmets/RysTHelmet.webp' 
import HelmetSfera from './Tarkov_Helmets/SferaInspect.PNG.webp' 
import HelmetSHPM from './Tarkov_Helmets/SHPM_Firefighter_helmet.webp' 
import HelmetSLock from './Tarkov_Helmets/Slockimage.webp' 
import HelmetSSH68 from './Tarkov_Helmets/SSH-68Image.webp' 
import HelmetTankhelm from './Tarkov_Helmets/TankHelm.webp' 
import HelmetExfil from './Tarkov_Helmets/Team_Wendy_EXFIL_Ballistic_Helmet.webp' 
import HelmetTKFast from './Tarkov_Helmets/TK_FAST_View.webp' 
import HelmetULACH from './Tarkov_Helmets/ULACH.webp' 
import HelmetUNTAR from './Tarkov_Helmets/UNTAR_Helmet.webp' 
import HelmetVulkan from './Tarkov_Helmets/Vulkan-5_LShZ-_heavy_helmet.webp' 
import HelmetZSH12M from './Tarkov_Helmets/ZSH-1-2M.webp' 
const Helmets = [
    [Helmet6B47,"6B47 'Ratnik-BSh' helmet"],[HelmetACHHC,"HighCom Striker ACHHC IIIA helmet"],[HelmetAltyn,"'Altyn' bulletproof helmet"],[HelmetArmasightnvg,"Armasight NVG head strap"],[HelmetBastion,"Diamond Age Bastion helmet"],[HelmetBomerBeanie,"Bomber beanie"],[HelmetCaiman,"Galvion Caiman Hybrid helmet"],[HelmetAirFrame,"Crye Precision AirFrame helmet"],[HelmetRonin,"DevTac Ronin ballistic helmet"],[HelmetFastmt,"Ops-Core FAST MT Super High Cut helmet"],[HelmetHJELM,"NFM 'HJELM' helmet"],[HelmetKiverM,"FORT Kiver-M bulletproof helmet"],[HelmetKolpak1S,"Kolpak-1S riot helmet"],[HelmetLSHZ,"BNTI LShZ-2DTM helmet"],[HelmetLZSh,"LShZ light helmet"],[HelmetMaska,"'Maska-1SCh' bulletproof helmet"],[HelmetMich2002,"MSA ACH TC-2002 MICH helmet"],[HelmetMich,"MSA ACH TC-2001 MICH helmet"],[HelmetMSATC800,"MSA Gallet TC 800 High Cut combat helmet"],[HelmetPSH97,"PSh-97 'DJETA' riot helmet"],[HelmetRysT,"'Rys-T' bulletproof helmet"],[HelmetSfera,"SSSh-94 'SFERA-S' helmet"],[HelmetSHPM,"ShPM Firefighter helmet"],[HelmetSLock,"Wilcox Skull Lock head mount"],[HelmetSSH68,"SSh-68 steel helmet"],[HelmetTankhelm,"TSh-4M-L soft tank crew helmet"],[HelmetExfil,"Team Wendy EXFIL Ballistic Helmet"],[HelmetTKFast,"Tac-Kek FAST MT helmet (replica)"],[HelmetULACH,"HighCom Striker ULACH IIIA helmet"],[HelmetUNTAR,"UNTAR helmet"],[HelmetVulkan,"'Vulkan-5' (LShZ-5) bulletproof helmet"],[HelmetZSH12M,"ZSh-1-2M helmet"]]
    export default Helmets;